# Generated by Django 3.1.2 on 2020-10-12 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officerooms', '0002_auto_20201012_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.PositiveIntegerField()),
                ('room_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='officerooms.room')),
            ],
        ),
        migrations.RenameField(
            model_name='bookinghistory',
            old_name='from_date',
            new_name='from_date_time',
        ),
        migrations.RenameField(
            model_name='bookinghistory',
            old_name='to_date',
            new_name='to_date_time',
        ),
        migrations.RemoveField(
            model_name='bookinghistory',
            name='room',
        ),
        migrations.RemoveField(
            model_name='bookinghistory',
            name='room_place',
        ),
        migrations.RemoveField(
            model_name='bookinghistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserPlace',
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='room_place_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='officerooms.roomplace'),
        ),
    ]
