# Generated by Django 3.1.2 on 2020-10-12 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officerooms', '0003_auto_20201012_1412'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookingHistory',
            new_name='BookingDetails',
        ),
    ]
