# Generated by Django 3.1.2 on 2020-10-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officerooms', '0005_auto_20201012_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
