# Generated by Django 3.1.2 on 2020-10-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officerooms', '0007_bookingdetails_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
